name: web-crawler-push

on:
  push:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: install-dependencies
        run: |
          cat >>requirements.txt<<EOF
          pytest==4.6.9
          EOF
          python3 -m pip install -r ./requirements.txt --user

      - name: unit-tests
        run: |
          python3 -m pytest -v -o log_cli=true ./crawler
